apiVersion: v1
kind: Service
metadata:
  name: mariadb
spec:
  clusterIP: None
  selector:
    app: mariadb
  ports:
    - port: 3306
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mariadb
spec:
  serviceName: "mariadb"
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
      - name: mariadb
        image: mariadb:10.11
        ports:
          - containerPort: 3306
        env:
          - name: MYSQL_USERNAME
            valueFrom:
              configMapKeyRef:
                name: lanchonete-config
                key: spring.datasource.username
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: lanchonete-secret
                key: spring.datasource.password
          - name: MYSQL_DATABASE
            valueFrom:
              configMapKeyRef:
                name: lanchonete-config
                key: spring.datasource.db-name
        volumeMounts:
          - name: mariadb-pvc
            mountPath: /var/lib/mysql
  volumeClaimTemplates:
    - metadata:
        name: mariadb-pvc
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 10Gi
